// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

type Activity struct {
	ID          int64
	Date        string
	IsCompleted int64
	HabitID     int64
}

type Habit struct {
	ID   int64
	Name string
}
