// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
)

const createActivity = `-- name: CreateActivity :exec
INSERT OR IGNORE INTO activity (date, is_completed, habit_name)
VALUES (?1, ?2, ?3)
`

type CreateActivityParams struct {
	Date        string
	IsCompleted int64
	HabitName   string
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) error {
	_, err := q.db.ExecContext(ctx, createActivity, arg.Date, arg.IsCompleted, arg.HabitName)
	return err
}

const createHabit = `-- name: CreateHabit :exec
INSERT INTO habit (name) VALUES (?1)
`

func (q *Queries) CreateHabit(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, createHabit, name)
	return err
}

const deleteActivity = `-- name: DeleteActivity :exec
DELETE FROM activity
WHERE date = ?1
  AND habit_name = ?2
`

type DeleteActivityParams struct {
	Date      string
	HabitName string
}

func (q *Queries) DeleteActivity(ctx context.Context, arg DeleteActivityParams) error {
	_, err := q.db.ExecContext(ctx, deleteActivity, arg.Date, arg.HabitName)
	return err
}

const listCompletedHabitActivities = `-- name: ListCompletedHabitActivities :many
SELECT date, is_completed, habit_name
FROM activity
WHERE is_completed = 1
  AND date >= ?1
  AND habit_name = ?2
ORDER BY date
`

type ListCompletedHabitActivitiesParams struct {
	LookbackStart string
	HabitName     string
}

type ListCompletedHabitActivitiesRow struct {
	Date        string
	IsCompleted int64
	HabitName   string
}

func (q *Queries) ListCompletedHabitActivities(ctx context.Context, arg ListCompletedHabitActivitiesParams) ([]ListCompletedHabitActivitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCompletedHabitActivities, arg.LookbackStart, arg.HabitName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompletedHabitActivitiesRow
	for rows.Next() {
		var i ListCompletedHabitActivitiesRow
		if err := rows.Scan(&i.Date, &i.IsCompleted, &i.HabitName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHabits = `-- name: ListHabits :many
SELECT name FROM habit ORDER BY name
`

func (q *Queries) ListHabits(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listHabits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
